meta_product_name: "TakeYourTime"
meta_title: "TakeYourTime - Stop for 15 minutes and improve your life."
meta_description: "Le plus grand secret pour le bonheur, c'est d'être bien avec soi. Bernard Fontenelle "
meta_image: "cover.png"
